# Generated by Django 5.2 on 2025-04-24 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hungry_app', '0004_alter_customer_user_alter_vendor_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.PositiveIntegerField(default=10.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderitem',
            name='sale_price',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=6),
            preserve_default=False,
        ),
    ]
