# Generated by Django 5.2 on 2025-04-24 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hungry_app', '0005_order_total_price_orderitem_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
